server:
  port: 8081
spring:
  application:
    name: "accounts"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
   import: "configserver:http://localhost:8071/" # config server port 8071
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true # lab 31
    compatibility-verifier:
      enabled: false # disable version check
management:
  endpoints:
    web:
      exposure:
        include: "*" # Lab 19, 31
        # include: info, shutdown # lab 22 info, lab 23 shutdown
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true
        
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka
      
info:
  app:
    name: "accounts"
    description: "Bank Accounts Application"
    version: "1.0.0"

logging:
  level:
    com:
      tus:
        accounts: DEBUG
        
resilience4j.circuitbreaker: # lab 31
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000 # 10 seconds