build:
  version: "2.2"
cards:
  message: "Welcome to card related prod APIs"
  contactDetails:
    name: "John Bloggs - Cards Prod Lead"
    email: "john@cards.ie"
  onCallSupport:
    - (086) 555-1234
    - (087) 523-1345