spring:
  application:
    name: gatewayserver
  config:
    import: "optional:configserver:http://localhost:8071" # Lab 22
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lower-case-service-id: true # lab 27
          httpclient:
            connect-timeout: 1000 # lab 32
            response-timeout: 5s  # lab 32
management:
  endpoints:
    web:
      exposure:
        include: "*" # Lab 19
  endpoint:
    gateway:
      # enabled: true # Lab 22
      access: unrestricted
  info:
    env:
      enabled: true
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka
info:
  app:
    name: "gatewayserver"
    description: "Bank Application Gateway Server"
    version: "1.0.0"

server:
  port: 8072
  
logging:
  level:
    com:
      tus:
        gatewayserver: DEBUG
        
resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000