build:
  version: "3.2"
loans:
  message: "Welcome to TUS loans related Prod APIs"
  contactDetails:
    name: "John Bloggs - Loan Prod Support"
    email: "john@loans.com"
  onCallSupport:
    - (123) 555-1234
    - (123) 523-1345