build:
  version: "1.1"
cards:
  message: "Welcome to TUS cards related prod APIs"
  contactDetails:
    name: "John Murphy - Product Owner"
    email: "john@tus.ie"
  onCallSupport:
    - (086) 656-8709
    - (087) 342-0956