spring:
  application:
    name: "eurekaserver"
  config:
    import: "optional:configserver:http://localhost:8071" # Lab 22
management:
  endpoints:
    web:
      exposure:
        include: "*" # Lab 19
  health:
    readinessState:
      enabled: true # Lab 22
    livenessState:
      enabled: true # Lab 22
  endpoint:
    health:
      probes:
        enabled: true # Lab 22